// LA COMMUNAUTÉ · ses textes, dans les deux langues. Le français vouvoie.
import { B } from '../data/bilingual'
import type { CommunityCategory } from '../lib/community'

export const CT = {
  title: B('The DojoBuro community', 'La communauté DojoBuro'),
  lead: B('Share your prompts, your wins and your questions with people who learn AI like you. Reading is open to all; a free account is enough to post.',
    "Partagez vos prompts, vos réussites et vos questions avec ceux qui apprennent l'IA comme vous. La lecture est ouverte à tous ; un compte gratuit suffit pour publier."),
  tabFeed: B('Community', 'Communauté'),
  tabAbout: B('About', 'À propos'),
  tabs: B('Community sections', 'Sections de la communauté'),
  all: B('All', 'Tout'),
  search: B('Search the community', 'Rechercher dans la communauté'),
  write: B('Write something...', 'Écrivez quelque chose...'),
  signInToPost: B('Sign in to post, comment and like', 'Connectez-vous pour publier, commenter et aimer'),
  signIn: B('Sign in', 'Se connecter'),
  joinTitle: B('Choose the name shown to the community', 'Choisissez le nom affiché dans la communauté'),
  joinBody: B('Your first name, or a pseudonym. Your email is never shown.', 'Votre prénom, ou un pseudonyme. Votre adresse e-mail n\'est jamais affichée.'),
  joinPlace: B('Your name', 'Votre nom'),
  join: B('Join', 'Rejoindre'),
  category: B('Category', 'Catégorie'),
  postTitle: B('Title', 'Titre'),
  postBody: B('Your message', 'Votre message'),
  publish: B('Publish', 'Publier'),
  cancel: B('Cancel', 'Annuler'),
  pinned: B('Pinned', 'Épinglé'),
  pin: B('Pin', 'Épingler'),
  unpin: B('Unpin', 'Désépingler'),
  like: B('Like', "J'aime"),
  comments: B('comments', 'commentaires'),
  comment1: B('comment', 'commentaire'),
  reply: B('Reply', 'Répondre'),
  delete: B('Delete', 'Supprimer'),
  edit: B('Edit', 'Modifier'),
  mediaHint: B('Paste a YouTube, Vimeo, Loom, Instagram or TikTok link: it shows as a player.', "Collez un lien YouTube, Vimeo, Loom, Instagram ou TikTok : il s'affichera en lecteur."),
  mediaPlay: B('Show the content from', 'Afficher le contenu de'),
  mediaPrivacy: B('Loads the player from this service, which may set its own cookies.', 'Charge le lecteur de ce service, qui peut déposer ses propres cookies.'),
  confirmDelete: B('Delete this for good?', 'Supprimer définitivement ?'),
  deleted: B('Deleted message', 'Message supprimé'),
  addComment: B('Your comment', 'Votre commentaire'),
  send: B('Send', 'Envoyer'),
  back: B('Back to the feed', 'Retour au fil'),
  more: B('Load more', 'Voir plus'),
  readMore: B('Read more', 'Lire la suite'),
  empty: B('Nothing here yet. Be the first to post.', 'Rien pour le moment. Publiez le premier message.'),
  noResult: B('No post matches this search.', 'Aucune publication ne correspond à cette recherche.'),
  loading: B('Loading...', 'Chargement...'),
  edited: B('edited', 'modifié'),
  offTitle: B('The community server is not set up yet', "Le serveur de la communauté n'est pas encore configuré"),
  offBody: B('This deployment has no database yet. Once it is connected, the feed appears here.', "Ce déploiement n'a pas encore de base de données. Une fois celle-ci branchée, le fil apparaîtra ici."),
  authOff: B('Signing in is not enabled on this deployment yet: you can read, not post.', "La connexion n'est pas encore activée sur ce déploiement : vous pouvez lire, pas publier."),
  network: B('The server did not answer. Try again in a moment.', 'Le serveur n\'a pas répondu. Réessayez dans un instant.'),
  rate: B('That is a lot in a short time. Wait a little before posting again.', 'Cela fait beaucoup en peu de temps. Patientez un peu avant de publier de nouveau.'),
  invalid: B('Something is missing: check the title (3 characters or more) and the message (10 characters or more).', 'Il manque quelque chose : vérifiez le titre (3 caractères au moins) et le message (10 caractères au moins).'),
  notFound: B('This post no longer exists.', "Cette publication n'existe plus."),
  tabMembers: B('Members', 'Membres'),
  tabCalendar: B('Calendar', 'Calendrier'),
  notifications: B('Notifications', 'Notifications'),
  messages: B('Messages', 'Messages'),
  noNotifications: B('No notification yet.', 'Aucune notification pour le moment.'),
  nComment: B('commented on your post', 'a commenté votre publication'),
  nReply: B('replied to your comment', 'a répondu à votre commentaire'),
  nLikePost: B('liked your post', 'a aimé votre publication'),
  nLikeComment: B('liked your comment', 'a aimé votre commentaire'),
  noConversations: B('No conversation yet. Open a member\'s profile to write to them.', "Aucune conversation pour le moment. Ouvrez le profil d'un membre pour lui écrire."),
  writeTo: B('Send a message', 'Envoyer un message'),
  yourMessage: B('Your message', 'Votre message'),
  you: B('You', 'Vous'),
  pickConversation: B('Choose a conversation.', 'Choisissez une conversation.'),
  signInMessages: B('Sign in to see your messages and notifications.', 'Connectez-vous pour voir vos messages et vos notifications.'),
  calH2: B('Calendar', 'Calendrier'),
  calLead: B('Lives, masterclasses and workshops of the community. Times are shown in your own time zone.', "Les lives, masterclass et ateliers de la communauté. Les horaires s'affichent dans votre fuseau horaire."),
  today: B('Today', "Aujourd'hui"),
  prevMonth: B('Previous month', 'Mois précédent'),
  nextMonth: B('Next month', 'Mois suivant'),
  upcoming: B('Coming up', 'À venir'),
  noEvents: B('No event planned yet.', 'Aucun événement prévu pour le moment.'),
  joinLive: B('Join the live', 'Rejoindre le live'),
  addToCalendar: B('Add to my calendar', 'Ajouter à mon agenda'),
  minutes: B('min', 'min'),
  newEvent: B('New event', 'Nouvel événement'),
  eventTitle: B('Title', 'Titre'),
  eventDate: B('Date', 'Date'),
  eventTime: B('Time', 'Heure'),
  eventDuration: B('Duration (minutes)', 'Durée (minutes)'),
  eventLink: B('Video link (https)', 'Lien de visio (https)'),
  eventDesc: B('Description', 'Description'),
  create: B('Create', 'Créer'),
  tabBoards: B('Leaderboards', 'Classements'),
  membersH2: B('Members', 'Membres'),
  membersCount: B('members', 'membres'),
  searchMembers: B('Search a member', 'Rechercher un membre'),
  online: B('Online', 'En ligne'),
  joined: B('Joined', 'Membre depuis'),
  level: B('Level', 'Niveau'),
  points: B('points', 'points'),
  noMembers: B('No member yet.', 'Aucun membre pour le moment.'),
  boardsH2: B('Leaderboards', 'Classements'),
  boardsLead: B('Points are the likes your posts and comments receive from others. Helping is what makes you climb.',
    "Les points sont les j'aime que vos publications et vos commentaires reçoivent des autres. C'est l'aide apportée qui fait monter."),
  week: B('Last 7 days', '7 derniers jours'),
  month: B('Last 30 days', '30 derniers jours'),
  allTime: B('All time', 'Depuis toujours'),
  noBoard: B('Nobody yet: the first likes will fill this board.', "Personne pour le moment : les premiers j'aime rempliront ce classement."),
  yourLevel: B('Your level', 'Votre niveau'),
  toNext: B('points to level', 'points avant le niveau'),
  maxLevel: B('You reached the highest level.', 'Vous avez atteint le niveau le plus élevé.'),
  levelsH3: B('The nine levels', 'Les neuf niveaux'),
  fromPoints: B('from', 'dès'),
  profilePosts: B('Posts', 'Publications'),
  profileComments: B('Comments', 'Commentaires'),
  editProfile: B('Edit my profile', 'Modifier mon profil'),
  bio: B('A few words about you', 'Quelques mots sur vous'),
  save: B('Save', 'Enregistrer'),
  saved: B('Saved', 'Enregistré'),
  own: B('Your own messages cannot be liked: points measure the help given to others.', "Vos propres messages ne peuvent pas être aimés : les points mesurent l'aide apportée aux autres."),
  noPosts: B('No post yet.', 'Aucune publication pour le moment.'),
  aboutH2: B('About this community', 'À propos de cette communauté'),
  aboutBody: B(
    'DojoBuro is where people learn to make AI work for them: short lessons, a game, and this community. Here you share what works, ask what does not, and help others move forward.',
    "DojoBuro est l'endroit où l'on apprend à faire travailler l'IA pour soi : des leçons courtes, un jeu, et cette communauté. On y partage ce qui fonctionne, on y demande ce qui bloque, et on aide les autres à avancer.",
  ),
  free: B('Free', 'Gratuit'),
  rulesH3: B('The rules', 'Les règles'),
  rules: [
    B('Be kind and precise: say what you tried and what you got.', 'Faites preuve de bienveillance et de précision : dites ce que vous avez essayé et ce que vous avez obtenu.'),
    B('No client data, no personal data, no secrets in your prompts.', 'Aucune donnée client, aucune donnée personnelle, aucun secret dans vos prompts.'),
    B('No advertising or unsolicited selling.', 'Pas de publicité ni de démarchage.'),
    B('Share your sources when you quote a figure.', 'Citez vos sources lorsque vous avancez un chiffre.'),
  ],
  startTraining: B('Start the free AI weekend', "Commencer le week-end de l'IA gratuit"),
}

export const CATEGORY_LABEL: Record<CommunityCategory, ReturnType<typeof B>> = {
  general: B('General', 'Général'),
  intro: B('Introductions', 'Présentations'),
  questions: B('Questions', 'Questions'),
  wins: B('Wins', 'Réussites'),
  prompts: B('Prompts', 'Prompts'),
  resources: B('Resources', 'Ressources'),
}
