// Business ledger · turns REAL in-app activity into finance transactions, so
// Finance & Analytics reflect what actually happens in the app (sales closed in
// the CRM, marketing budgets set in Campaign), not just imported CSVs. 100% local.
import { type Txn, loadFinance } from './finance'
import { loadCrm } from './crm'
import { loadCampaign } from './campaign'

const iso = (ms: number) => new Date(ms).toISOString().slice(0, 10)

/** Transactions generated by the app itself (read-only in Finance). */
export async function appTransactions(dojoId: string): Promise<Txn[]> {
  const out: Txn[] = []

  // CRM deals marked "Won" = real revenue, dated when they were won
  const crm = await loadCrm(dojoId)
  for (const c of crm?.contacts ?? []) {
    if (c.stage === 'gagne' && c.value > 0) {
      out.push({
        id: 'crm_' + c.id,
        date: iso(c.wonAt ?? Date.now()),
        label: `Sale — ${c.name}${c.company ? ' (' + c.company + ')' : ''}`,
        amount: c.value,
        category: 'Sales',
        source: 'app',
      })
    }
  }

  // Campaign marketing budget = real spend
  const camp = await loadCampaign(dojoId)
  if (camp?.budget && camp.budget > 0) {
    out.push({
      id: 'camp_budget',
      date: iso(camp.updatedAt || Date.now()),
      label: `Meta ad budget — ${camp.product || 'campaign'}`,
      amount: -camp.budget,
      category: 'Marketing',
      source: 'app',
    })
  }

  return out.sort((a, b) => b.date.localeCompare(a.date))
}

/** App activity + the user's manual/imported transactions (the full picture). */
export async function allTransactions(dojoId: string): Promise<Txn[]> {
  const [app, fin] = await Promise.all([appTransactions(dojoId), loadFinance(dojoId)])
  const manual = (fin?.txns ?? []).map((t) => ({ ...t, source: t.source ?? ('manual' as const) }))
  return [...app, ...manual]
}
