// LES TEMPLES · leurs textes, dans les deux langues. Le français vouvoie.
import { B } from '../data/bilingual'

export const TT = {
  worldTitle: B('The temples of Dojoburo', 'Les temples de Dojoburo'),
  worldLead: B('Each temple is a training, each floor a lesson. The first temple is free; the others open when you unlock them.',
    "Chaque temple est une formation, chaque étage une leçon. Le premier temple est gratuit ; les autres s'ouvrent quand vous les débloquez."),
  coursesH2: B('The trainings', 'Les formations'),
  floors: B('floors', 'étages'),
  floor: B('Floor', 'Étage'),
  free: B('Free', 'Gratuit'),
  locked: B('Locked', 'Verrouillé'),
  open: B('Open', 'Ouvert'),
  freeLessons: B('free lessons', 'leçons offertes'),
  testerNote: B('Test access is on in this browser: every temple opens for you, the padlocks show what a learner sees.', "L'accès d'essai est actif sur ce navigateur : tous les temples vous sont ouverts, les cadenas montrent ce que voit un élève."),
  dailyChallenge: B("Today's challenge:", 'Défi du jour :'),
  askMaster: B('Ask me your questions about the course here: I am an AI and I answer when you end with a question mark.', "Posez-moi ici vos questions sur le cours : je suis une IA, et je réponds quand votre message se termine par un point d'interrogation."),
  masterThinking: B('writing an answer', 'écrit une réponse'),
  testifyH: B('You finished this training', 'Vous avez terminé cette formation'),
  testifyBody: B('Congratulations. If you wish, tell the community in a few lines what it changed for you: your testimonial is published with your agreement, after review.', "Félicitations. Si vous le souhaitez, racontez en quelques lignes ce qu'elle a changé pour vous : votre témoignage est publié avec votre accord, après relecture."),
  testifyGo: B('Leave a testimonial', 'Déposer un témoignage'),
  musicOn: B('Play the zen music', 'Jouer la musique zen'),
  musicOff: B('Mute the zen music', 'Couper la musique zen'),
  openWithEmail: B('Open with my email', 'Ouvrir avec mon adresse'),
  enter: B('Enter the temple', 'Entrer dans le temple'),
  back: B('Back to the temples', 'Retour aux temples'),
  up: B('Go up one floor', "Monter d'un étage"),
  down: B('Go down one floor', "Descendre d'un étage"),
  map: B('Floors of the temple', 'Étages du temple'),
  door: B('Take the door to the next floor', "Prendre la porte vers l'étage suivant"),
  topFloor: B('This is the top floor.', 'Vous êtes au dernier étage.'),
  master: B('Master', 'Maître'),
  talkMaster: B('Talk to the master', 'Parler au maître'),
  startLesson: B('Start the lesson', 'Commencer le cours'),
  redoLesson: B('Redo the lesson', 'Refaire le cours'),
  close: B('Close', 'Fermer'),
  you: B('You', 'Vous'),
  done: B('Done', 'Terminé'),
  lockedFloor: B('This floor is locked', 'Cet étage est verrouillé'),
  unlock: B('Unlock the temple', 'Débloquer le temple'),
  emailGate: B('Your email opens the seven floors of the free temple.', 'Votre adresse e-mail ouvre les sept étages du temple gratuit.'),
  chat: B('Chat', 'Chat'),
  present: B('Studying here now', 'Étudient ici en ce moment'),
  nobody: B('Nobody else on this temple right now.', "Personne d'autre dans ce temple pour le moment."),
  groupChat: B('Course group', 'Groupe du cours'),
  privateMsg: B('Private message', 'Message privé'),
  signInChat: B('Sign in to see who studies here and talk with them.', 'Connectez-vous pour voir qui étudie ici et échanger avec eux.'),
  signIn: B('Sign in', 'Se connecter'),
  writeGroup: B('Write to the group...', 'Écrire au groupe...'),
  send: B('Send', 'Envoyer'),
  noMessages: B('No message yet. Say hello to the group.', 'Aucun message pour le moment. Saluez le groupe.'),
  chooseTitle: B('Choose your character', 'Choisissez votre personnage'),
  chooseLead: B('It represents you in the temples: the other students see it on your floor.', "Il vous représente dans les temples : les autres élèves le voient à votre étage."),
  choose: B('Create my character', 'Créer mon personnage'),
  editCharacter: B('Edit my character', 'Modifier mon personnage'),
  lessonBy: B('Lesson given by Master', 'Leçon donnée par Maître'),
  fullscreen: B('Full screen', 'Plein écran'),
}
