// LES FORMATIONS ET LEURS COURS · leurs textes, dans les deux langues. Le
// français vouvoie. Demandé : « parle que de formation et cours plus de
// temples ». Les temples et les étages restent le décor ; les mots disent
// formation (l'ensemble) et cours (une leçon).
import { B } from '../data/bilingual'

export const TT = {
  worldTitle: B('Learn AI with Dojoburo', "Apprenez l'IA avec Dojoburo"),
  worldLead: B('Choose your AI course on the map.', 'Choisissez votre formation IA sur la carte.'),
  allCourses: B('See every course, its master and its price', 'Voir toutes les formations, leurs maîtres et leurs prix'),
  coursesH2: B('The courses', 'Les formations'),
  floors: B('lessons', 'cours'),
  floor: B('Lesson', 'Cours'),
  free: B('Free', 'Gratuit'),
  locked: B('Locked', 'Verrouillé'),
  open: B('Open', 'Ouvert'),
  freeLessons: B('free lessons', 'cours offerts'),
  dailyChallenge: B("Today's challenge:", 'Défi du jour :'),
  askMaster: B('Ask me your questions about the course here: I am an AI and I answer when you end with a question mark.', "Posez-moi ici vos questions sur le cours : je suis une IA, et je réponds quand votre message se termine par un point d'interrogation."),
  masterThinking: B('writing an answer', 'écrit une réponse'),
  testifyH: B('You finished this training', 'Vous avez terminé cette formation'),
  testifyBody: B('Congratulations. If you wish, tell the community in a few lines what it changed for you: your testimonial is published with your agreement, after review.', "Félicitations. Si vous le souhaitez, racontez en quelques lignes ce qu'elle a changé pour vous : votre témoignage est publié avec votre accord, après relecture."),
  testifyGo: B('Leave a testimonial', 'Déposer un témoignage'),
  musicOn: B('Play the zen music', 'Jouer la musique zen'),
  musicOff: B('Mute the zen music', 'Couper la musique zen'),
  openWithEmail: B('Open with my email', 'Ouvrir avec mon adresse'),
  enter: B('Open the course', 'Ouvrir la formation'),
  back: B('Back to the courses', 'Retour aux formations'),
  up: B('Next lesson', 'Cours suivant'),
  down: B('Previous lesson', 'Cours précédent'),
  map: B('Lessons of the course', 'Cours de la formation'),
  door: B('Go to the next lesson', 'Passer au cours suivant'),
  topFloor: B('This is the last lesson of the course.', 'Vous êtes au dernier cours de la formation.'),
  master: B('Master', 'Maître'),
  talkMaster: B('Talk to the master', 'Parler au maître'),
  startLesson: B('Start the lesson', 'Commencer le cours'),
  redoLesson: B('Redo the lesson', 'Refaire le cours'),
  close: B('Close', 'Fermer'),
  you: B('You', 'Vous'),
  done: B('Done', 'Terminé'),
  lockedFloor: B('This lesson is locked', 'Ce cours est verrouillé'),
  unlock: B('Unlock the course', 'Débloquer la formation'),
  emailGate: B('Your email opens the seven lessons of the free course.', 'Votre adresse e-mail ouvre les sept cours de la formation gratuite.'),
  chat: B('Chat', 'Chat'),
  present: B('Studying here now', 'Étudient ici en ce moment'),
  nobody: B('Nobody else on this course right now.', "Personne d'autre sur cette formation pour le moment."),
  groupChat: B('Course group', 'Groupe de la formation'),
  privateMsg: B('Private message', 'Message privé'),
  signInChat: B('Sign in to see who studies here and talk with them.', 'Connectez-vous pour voir qui étudie ici et échanger avec eux.'),
  signIn: B('Sign in', 'Se connecter'),
  writeGroup: B('Write to the group...', 'Écrire au groupe...'),
  send: B('Send', 'Envoyer'),
  noMessages: B('No message yet. Say hello to the group.', 'Aucun message pour le moment. Saluez le groupe.'),
  chooseTitle: B('Choose your character', 'Choisissez votre personnage'),
  chooseLead: B('It represents you on the map and in the community: the other learners see it in the lesson you are taking.', 'Il vous représente sur la carte et dans la communauté : les autres élèves le voient dans le cours que vous suivez.'),
  choose: B('Create my character', 'Créer mon personnage'),
  editCharacter: B('Edit my character', 'Modifier mon personnage'),
  lessonBy: B('Lesson given by Master', 'Cours donné par le maître'),
  fullscreen: B('Full screen', 'Plein écran'),
}
