// LE COURS « Coder une app avec Lovable » · voir ./types et ./index.
//
// UN SEUL FIL ROUGE, DU PREMIER AU DERNIER DOJO · « Atelier », l'app de
// réservation d'un petit atelier de poterie. Les visiteurs voient les
// prochaines séances, créent un compte et réservent une place ; la
// propriétaire gère les séances. Chaque dojo fait avancer cette même app :
// on la comprend, on la branche, on apprend à la demander, on la construit,
// on la sécurise et on la publie.
//
// CE QUE LE COURS AFFIRME DE LOVABLE, ET CE QU'IL S'INTERDIT. Il s'en tient
// aux faits stables : la stack générée (React, Vite, TypeScript, Tailwind CSS,
// shadcn/ui), les deux façons de parler à l'outil (planifier sans modifier,
// ou modifier), la connaissance du projet, l'historique des versions, le
// backend Supabase ou intégré, la synchronisation GitHub dans les deux sens,
// la publication. Les libellés exacts de l'interface et les limites des offres
// bougent : le cours décrit le principe et renvoie à la documentation et à la
// grille tarifaire officielles, sans jamais citer de chiffre.
import { B } from '../bilingual'
import type { Level, Module } from '../curriculum'
import type { Enrichment } from '../enrich/types'
import type { Deepening } from '../deep/types'
import { enrichKey } from '../enrich/types'
import { deepKey } from '../deep/types'
import type { CoursePart } from './types'

/* ================================================================== */
/* CITÉ 1 · COMPRENDRE LOVABLE                                         */
/* ================================================================== */

const M1 = 'lv-start'

const START: Level[] = [
  {
    id: 'lv-what',
    master: 'research',
    minutes: 9,
    title: B('What Lovable builds, and how', 'Ce que Lovable construit, et comment'),
    learn: B(
      'You will know what Lovable produces from a prompt: a React, Vite, TypeScript and Tailwind project that you own.',
      "Vous saurez ce que Lovable produit à partir d'un prompt : un projet React, Vite, TypeScript et Tailwind qui vous appartient.",
    ),
    act: B('Create the Atelier project with a short prompt, then locate its stack and its main files in the code view.',
      'Créez le projet Atelier avec un court prompt, puis repérez sa stack et ses fichiers principaux dans la vue du code.'),
    steps: [
      B('Describe Atelier in three lines: a pottery workshop, its upcoming sessions, a seat to book.',
        'Décrivez Atelier en trois lignes : un atelier de poterie, ses prochaines séances, une place à réserver.'),
      B('Watch the preview appear: it is a running app, built on code that was just written for you.',
        "Observez la preview qui apparaît : c'est une app qui tourne, bâtie sur du code qui vient d'être écrit pour vous."),
      B('Open the code view and find package.json, src/App.tsx and the src/components/ui folder.',
        'Ouvrez la vue du code et repérez package.json, src/App.tsx et le dossier src/components/ui.'),
      B('Name each layer: React for screens, Vite to run them, Tailwind for style, shadcn/ui for components.',
        'Nommez chaque couche : React pour les écrans, Vite pour les servir, Tailwind pour le style, shadcn/ui pour les composants.'),
    ],
    trap: B(
      'Taking the preview for a mock-up: it is a real app, and its code will have to be maintained, secured and understood, by you.',
      "Prendre la preview pour une maquette : c'est une vraie app, dont le code devra être maintenu, sécurisé et compris, par vous.",
    ),
    quiz: {
      q: B('Where does the code of the Atelier app generated by Lovable actually live?',
        "Où vit réellement le code de l'app Atelier générée par Lovable ?"),
      options: [
        B('In a proprietary format that only the Lovable editor can open and run', "Dans un format propriétaire que seul l'éditeur Lovable sait ouvrir"),
        B('In a standard React project, which you can sync to GitHub', 'Dans un projet React standard, que vous pouvez synchroniser avec GitHub'),
        B('Nowhere: the app is redrawn from your prompt on every single visit', "Nulle part : l'app est redessinée à partir du prompt à chaque visite"),
      ],
      answer: 1,
      why: B(
        'Lovable writes ordinary source files: React components, TypeScript, Tailwind classes. That is why the code can be synced to GitHub, read, and continued with other tools.',
        'Lovable écrit des fichiers sources ordinaires : composants React, TypeScript, classes Tailwind. Le code peut donc être synchronisé avec GitHub, relu et poursuivi avec d\'autres outils.',
      ),
    },
    badge: B('Knows what lies under the preview', 'Sait ce qui se cache sous la preview'),
  },
  {
    id: 'lv-modes',
    master: 'planning',
    minutes: 9,
    title: B('Plan in chat, then let it edit', 'Planifier en discussion, puis le laisser modifier'),
    learn: B(
      'You will choose between planning with Lovable without touching the code and letting it edit, and keep each request small.',
      'Vous saurez choisir entre planifier avec Lovable sans toucher au code et le laisser modifier, en gardant chaque demande petite.',
    ),
    act: B('Plan the booking form of Atelier in chat mode, correct the plan, then have it built in one precise request.',
      "Planifiez le formulaire de réservation d'Atelier en mode discussion, corrigez le plan, puis faites-le construire."),
    steps: [
      B('Switch to chat mode and ask how Lovable would add a booking form, without changing any file.',
        'Passez en mode discussion et demandez comment Lovable ajouterait un formulaire de réservation, sans modifier de fichier.'),
      B('Read the plan: fields, files touched, validation. Correct anything that is not what you want.',
        "Lisez le plan : champs, fichiers touchés, validation. Corrigez ce qui ne correspond pas à votre intention."),
      B('Return to the default mode and ask for that plan only, in one message with one goal.',
        'Revenez au mode par défaut et demandez ce plan seulement, en un message qui porte un seul objectif.'),
      B('Check the preview, then the credits used, and compare with a vague request you made earlier.',
        'Vérifiez la preview, puis les crédits consommés, et comparez avec une demande vague faite plus tôt.'),
    ],
    trap: B(
      'Sending "add bookings, accounts, an admin area and payments" in one message: many files change at once, and nothing can be checked.',
      "Envoyer « ajoute les réservations, les comptes, un espace admin et le paiement » d'un coup : trop de fichiers changent, rien ne se vérifie.",
    ),
    quiz: {
      q: B('You are unsure how Lovable will structure the booking form. What do you do first?',
        "Vous ne savez pas comment Lovable structurera le formulaire de réservation. Que faites-vous d'abord ?"),
      options: [
        B('Let it build the form and undo it later if the result is wrong', 'Vous le laissez construire, quitte à annuler si le résultat déplaît'),
        B('Write the whole form yourself in the code view to save credits', 'Vous écrivez tout le formulaire dans la vue du code pour économiser'),
        B('Ask in chat mode for a plan, then correct it before any edit', 'Vous demandez un plan en mode discussion et le corrigez avant tout'),
      ],
      answer: 2,
      why: B(
        'Chat mode lets Lovable reason about your project without editing files. Correcting a plan costs one short message; undoing a wrong build costs a restore and a second try.',
        "Le mode discussion fait raisonner Lovable sur le projet sans modifier de fichier. Corriger un plan coûte un court message ; défaire une construction ratée coûte une restauration et un nouvel essai.",
      ),
    },
    badge: B('Plans before it builds', 'Planifie avant de construire'),
  },
  {
    id: 'lv-anatomy',
    master: 'coding',
    minutes: 10,
    title: B('Anatomy of a Lovable project', "L'anatomie d'un projet Lovable"),
    learn: B(
      'You will read a Lovable project: pages, components, routes, styles, and know when a visual edit beats a prompt.',
      "Vous saurez lire un projet Lovable : pages, composants, routes, styles, et quand une retouche visuelle vaut mieux qu'un prompt.",
    ),
    act: B('Map the files of Atelier, add the route of a session page, then fix a heading with a visual edit.',
      "Cartographiez les fichiers d'Atelier, ajoutez la route d'une page séance, puis corrigez un titre en retouche visuelle."),
    steps: [
      B('In the code view, list the files under src/pages and src/components, and say what each one shows.',
        'Dans la vue du code, listez les fichiers de src/pages et src/components, et dites ce que chacun affiche.'),
      B('Read src/App.tsx: each route links an address, such as /sessions/:id, to a page component.',
        'Lisez src/App.tsx : chaque route relie une adresse, comme /sessions/:id, à un composant de page.'),
      B('Ask for a session page at /sessions/:id, then check that a new file and a new route appeared.',
        "Demandez une page séance à l'adresse /sessions/:id, puis vérifiez qu'un fichier et une route sont apparus."),
      B('Select the home heading in the preview and change its text and size with a visual edit.',
        "Sélectionnez le titre d'accueil dans la preview et changez son texte et sa taille par retouche visuelle."),
    ],
    trap: B(
      'Spending a prompt to change a word or a color: a visual edit does it directly, and the prompt may rewrite more than the heading.',
      'Dépenser un prompt pour changer un mot ou une couleur : la retouche visuelle le fait directement, le prompt peut réécrire plus que le titre.',
    ),
    quiz: {
      q: B('The session page exists in src/pages, yet /sessions/12 shows a "not found" page. Where do you look first?',
        "La page séance existe dans src/pages, pourtant /sessions/12 affiche « page introuvable ». Où regardez-vous d'abord ?"),
      options: [
        B('In the routes declared in src/App.tsx', 'Dans les routes déclarées dans src/App.tsx'),
        B('In tailwind.config.ts, where the page styles are set', 'Dans tailwind.config.ts, où se règlent les styles des pages'),
        B('In the components of src/components/ui, used by every page', 'Dans les composants de src/components/ui, utilisés partout'),
      ],
      answer: 0,
      why: B(
        'A page file is only reachable once a route points to it. In a Lovable project, the routes are declared in src/App.tsx; a page missing from there shows the not found screen.',
        "Un fichier de page n'est accessible que si une route y mène. Dans un projet Lovable, les routes sont déclarées dans src/App.tsx ; une page absente de cette liste mène à l'écran introuvable.",
      ),
    },
    badge: B('Reads the map of the project', 'Lit la carte du projet'),
  },
]

const START_ENRICH: Record<string, Enrichment> = {
  [enrichKey(M1, 'lv-what')]: {
    why: [
      B("Lovable is a chat placed in front of a code generator. Each message you send is turned by a model into changes to the files of a real project; the project is then built and shown in the preview. Nothing is drawn by hand: what you see is what the code does, and what the code does not do, the preview cannot show.",
        "Lovable est une conversation placée devant un générateur de code. Chaque message envoyé est traduit par un modèle en modifications des fichiers d'un vrai projet ; ce projet est ensuite compilé et affiché dans la preview. Rien n'est dessiné à la main : ce que vous voyez est ce que fait le code, et ce que le code ne fait pas, la preview ne peut pas le montrer."),
      B("The stack is fixed and widespread: React for the interface, Vite to build and serve it, TypeScript for types, Tailwind CSS for styling and shadcn/ui for ready-made components such as forms, dialogs and tables. Because these tools are so common, the model writes them well, and any developer, or another AI tool, can take the code over later.",
        "La stack est fixe et très répandue : React pour l'interface, Vite pour la compiler et la servir, TypeScript pour les types, Tailwind CSS pour le style et shadcn/ui pour des composants prêts à l'emploi, comme les formulaires, les fenêtres et les tableaux. Ces outils étant très courants, le modèle les écrit bien, et n'importe quel développeur, ou un autre outil IA, peut reprendre le code ensuite."),
      B("The code lives in the project, not in the conversation. You can read it in the code view and sync it to a GitHub repository you own. Keeping this in mind changes how you work: you are not ordering screens, you are steering the writing of a codebase you will answer for.",
        "Le code vit dans le projet, pas dans la conversation. Vous pouvez le lire dans la vue du code et le synchroniser avec un dépôt GitHub qui vous appartient. Garder cela à l'esprit change la manière de travailler : vous ne commandez pas des écrans, vous dirigez l'écriture d'un code dont vous répondrez."),
    ],
    example: {
      context: B("Inès runs a small pottery workshop and wants a booking app called Atelier. Her first message is vague, and afterwards she cannot tell what was built or why.",
        "Inès tient un petit atelier de poterie et veut une app de réservation nommée Atelier. Son premier message est vague, et elle ne sait plus ensuite ce qui a été construit, ni pourquoi."),
      before: B("Make me a nice website for my pottery workshop.",
        "Fais-moi un joli site pour mon atelier de poterie."),
      after: B("Create a web app called Atelier for a small pottery workshop.\nPages: a home page listing the upcoming sessions (date, time, theme, seats left), and one page per session with a booking form (name, email, number of seats).\nFor now, use sample data written in the code: no database yet.\nStyle: warm and simple, earthy tones, easy to read on a phone.\nDo not add a blog, a shop or a login at this stage.",
        "Crée une app web nommée Atelier pour un petit atelier de poterie.\nPages : un accueil qui liste les prochaines séances (date, heure, thème, places restantes), et une page par séance avec un formulaire de réservation (nom, email, nombre de places).\nPour l'instant, utilise des données d'exemple écrites dans le code : pas encore de base de données.\nStyle : chaleureux et simple, tons terre, lisible sur téléphone.\nN'ajoute ni blog, ni boutique, ni connexion à ce stade."),
      takeaway: B("The second prompt names the pages, the data shown, the style and what to leave out. Inès knows what to look for in the preview and in the code view, so she checks the result instead of discovering it.",
        "Le second prompt nomme les pages, les données affichées, le style et ce qu'il faut laisser de côté. Inès sait quoi chercher dans la preview et dans la vue du code : elle vérifie le résultat au lieu de le découvrir."),
    },
    exercise: {
      goal: B("A first Atelier project whose stack and main files you can name, with written notes on what was generated.",
        "Un premier projet Atelier dont vous savez nommer la stack et les fichiers principaux, avec des notes écrites sur ce qui a été généré."),
      prompt: B("Create a web app called Atelier for [NAME OF THE WORKSHOP, REAL OR FICTIONAL].\nPages: a home page listing the upcoming sessions with [THE INFORMATION TO SHOW], and one page per session with a booking form.\nUse sample data in the code for now, no database.\nStyle: [THREE WORDS FOR THE STYLE].\nDo not add: [WHAT YOU DO NOT WANT YET].\nWhen you are done, list the files you created and what each one does.",
        "Crée une app web nommée Atelier pour [NOM DE L'ATELIER, RÉEL OU FICTIF].\nPages : un accueil qui liste les prochaines séances avec [LES INFORMATIONS À AFFICHER], et une page par séance avec un formulaire de réservation.\nUtilise pour l'instant des données d'exemple dans le code, sans base de données.\nStyle : [TROIS MOTS POUR LE STYLE].\nN'ajoute pas : [CE QUE VOUS NE VOULEZ PAS ENCORE].\nQuand tu as terminé, liste les fichiers créés et le rôle de chacun."),
      check: [
        B("The preview shows the session list and at least one session page", "La preview affiche la liste des séances et au moins une page séance"),
        B("You found package.json and can point to React, Vite and Tailwind in it", "Vous avez trouvé package.json et y repérez React, Vite et Tailwind"),
        B("You located the pages under src/pages and the routes in src/App.tsx", "Vous avez localisé les pages dans src/pages et les routes dans src/App.tsx"),
        B("Nothing you excluded, such as a login or a shop, appears in the app", "Rien de ce que vous avez exclu, connexion ou boutique, n'apparaît dans l'app"),
      ],
      bonus: B("Compare the file list Lovable gave you with the code view. If it mentions a file that does not exist, or a file exists that it never mentioned, note it: you have just checked what the model says against the code.",
        "Comparez la liste de fichiers donnée par Lovable avec la vue du code. S'il cite un fichier absent, ou si un fichier existe sans avoir été cité, notez-le : vous venez de confronter ce que dit le modèle au code réel."),
    },
    more: [
      { q: B("Why does Lovable generate React, TypeScript and Tailwind rather than a format of its own?",
          "Pourquoi Lovable génère-t-il du React, du TypeScript et du Tailwind plutôt qu'un format maison ?"),
        options: [
          B("Because a widespread stack is well written by models and easy to take over", "Parce qu'une stack répandue est bien écrite par les modèles et facile à reprendre"),
          B("Because browsers today refuse to run any other kind of front-end web code", "Parce que les navigateurs refusent aujourd'hui tout autre type de code web"),
          B("Because these tools let the app run without any server, on any device, forever", "Parce que ces outils permettent à l'app de tourner sans aucun serveur, à jamais"),
        ],
        answer: 0,
        why: B("Models write best what they have seen most, and React with Tailwind is everywhere. The same choice makes the code readable by developers and continuable with other tools once it is synced to GitHub.",
          "Les modèles écrivent le mieux ce qu'ils ont le plus vu, et React avec Tailwind est partout. Le même choix rend le code lisible par des développeurs et poursuivable avec d'autres outils une fois synchronisé avec GitHub.") },
      { q: B("The preview of Atelier shows a seats left counter, but you never asked for one. What does that tell you?",
          "La preview d'Atelier affiche un compteur de places restantes que vous n'avez jamais demandé. Qu'en déduisez-vous ?"),
        options: [
          B("Nothing: the preview adds decorative elements that the code does not contain", "Rien : la preview ajoute des éléments décoratifs absents du code"),
          B("The model made a choice for you, now written in the code, to keep or remove", "Le modèle a fait un choix à votre place, désormais écrit dans le code"),
          B("Lovable copied the counter from another project that you opened before", "Lovable a copié le compteur depuis un autre projet que vous avez ouvert"),
        ],
        answer: 1,
        why: B("The preview only shows what the code does. An element you did not request is a decision the model took to fill a gap. Decide whether to keep it, and say so in your next prompt.",
          "La preview ne montre que ce que fait le code. Un élément non demandé est une décision prise par le modèle pour combler un vide. Décidez de le garder ou non, et dites-le dans le prompt suivant.") },
    ],
  },

  [enrichKey(M1, 'lv-modes')]: {
    why: [
      B("Lovable offers two ways of talking to it. In chat mode, it reads your project, reasons and answers, but does not edit files: it is the place to ask how something works, to compare options or to get a plan. In the default mode, each message can change code. The labels may evolve; the distinction stays: thinking with the tool, or letting it act.",
        "Lovable propose deux façons de lui parler. En mode discussion (Chat mode), il lit le projet, raisonne et répond, sans modifier de fichier : c'est là que l'on demande comment une chose fonctionne, que l'on compare des options ou que l'on obtient un plan. Dans le mode par défaut, chaque message peut modifier le code. Les libellés peuvent évoluer ; la distinction demeure : réfléchir avec l'outil, ou le laisser agir."),
      B("Usage is counted in credits, drawn by your messages, and the amount and the rules depend on your plan: check the current pricing page rather than any figure you read elsewhere. What stays true is the logic: a large, vague request makes the model touch many files, and if the result is wrong you pay again to fix or redo it.",
        "L'usage se compte en crédits, consommés par vos messages, et leur volume comme leurs règles dépendent de votre offre : consultez la grille tarifaire actuelle plutôt qu'un chiffre lu ailleurs. Ce qui reste vrai, c'est la logique : une demande large et vague fait toucher beaucoup de fichiers au modèle, et si le résultat est faux, vous payez encore pour corriger ou recommencer."),
      B("A small, precise request has one goal, touches few files and can be checked in the preview in a minute. If it goes wrong, the version to restore is just before it. This is why planning first and editing in small steps is not only cheaper: it produces better code, because each change is understood before the next one starts.",
        "Une demande petite et précise porte un seul objectif, touche peu de fichiers et se vérifie dans la preview en une minute. Si elle échoue, la version à restaurer est juste avant. Planifier d'abord puis modifier par petits pas n'est donc pas seulement plus économique : le code est meilleur, parce que chaque changement est compris avant que le suivant commence."),
    ],
    example: {
      context: B("Inès wants visitors to book a seat in Atelier. She sends one long request, Lovable rewrites six files, and the session page no longer opens.",
        "Inès veut que les visiteurs réservent une place dans Atelier. Elle envoie une longue demande, Lovable réécrit six fichiers, et la page séance ne s'ouvre plus."),
      before: B("Add bookings to Atelier with a form, confirmation emails, user accounts, an admin page and online payment.",
        "Ajoute les réservations à Atelier avec un formulaire, des emails de confirmation, des comptes utilisateurs, une page admin et le paiement en ligne."),
      after: B("(Chat mode) Do not change any file yet.\nI want a booking form on the session page of Atelier: name, email, number of seats (1 to 4).\nExplain how you would do it: which files you would touch, which component from the UI library you would use, how you would validate the fields.\nTell me what you would need to decide that I have not specified.\n\n(Then, in the default mode) Implement the plan we agreed on, and only that. Keep the sample data; no database yet.",
        "(Mode discussion) Ne modifie encore aucun fichier.\nJe veux un formulaire de réservation sur la page séance d'Atelier : nom, email, nombre de places (de 1 à 4).\nExplique comment tu t'y prendrais : quels fichiers tu toucherais, quel composant de la bibliothèque d'interface tu utiliserais, comment tu validerais les champs.\nDis-moi ce que tu devrais décider et que je n'ai pas précisé.\n\n(Puis, dans le mode par défaut) Mets en oeuvre le plan convenu, et seulement lui. Garde les données d'exemple ; pas encore de base de données."),
      takeaway: B("The first message settles the plan without touching code; the second carries one goal and a boundary. The form arrives in two files, the session page still opens, and accounts and payment wait for their own turn.",
        "Le premier message arrête le plan sans toucher au code ; le second porte un objectif et une limite. Le formulaire arrive en deux fichiers, la page séance s'ouvre toujours, et les comptes comme le paiement attendront leur tour."),
    },
    exercise: {
      goal: B("A booking form planned in chat mode, corrected, then built in a single precise request, with a note on the credits it used.",
        "Un formulaire de réservation planifié en mode discussion, corrigé, puis construit en une seule demande précise, avec une note sur les crédits consommés."),
      prompt: B("(Chat mode) Do not edit any file.\nIn Atelier, I want [THE FEATURE, E.G. A BOOKING FORM ON THE SESSION PAGE].\nFields or behaviour: [WHAT IT MUST DO, WITH LIMITS].\nGive me a plan: files you would touch, components you would use, how you would validate the input.\nList the decisions I have left open.\n\n(After correcting the plan, default mode) Implement exactly the plan we agreed on. Do not change [WHAT MUST STAY AS IT IS].",
        "(Mode discussion) Ne modifie aucun fichier.\nDans Atelier, je veux [LA FONCTIONNALITÉ, PAR EXEMPLE UN FORMULAIRE DE RÉSERVATION SUR LA PAGE SÉANCE].\nChamps ou comportement : [CE QU'ELLE DOIT FAIRE, AVEC SES LIMITES].\nDonne-moi un plan : fichiers touchés, composants utilisés, validation des saisies.\nListe les décisions que j'ai laissées ouvertes.\n\n(Après correction du plan, mode par défaut) Mets en oeuvre exactement le plan convenu. Ne modifie pas [CE QUI DOIT RESTER TEL QUEL]."),
      check: [
        B("No file changed while you were in chat mode", "Aucun fichier n'a changé pendant que vous étiez en mode discussion"),
        B("You corrected or confirmed every open decision before building", "Vous avez tranché chaque décision ouverte avant de construire"),
        B("The edit touched only the files announced in the plan", "La modification n'a touché que les fichiers annoncés dans le plan"),
        B("The preview shows the form and the rest of Atelier still works", "La preview montre le formulaire et le reste d'Atelier fonctionne toujours"),
      ],
      bonus: B("Look at the credits used by this two-step request and by your vaguest earlier message. Do not keep a figure as a rule, since plans change, but keep the comparison: it tells you what a precise request is worth.",
        "Regardez les crédits consommés par cette demande en deux temps et par votre message le plus vague. Ne retenez pas un chiffre comme règle, les offres changent, mais gardez la comparaison : elle dit ce que vaut une demande précise."),
    },
    more: [
      { q: B("What does chat mode do that the default mode does not?",
          "Que fait le mode discussion que le mode par défaut ne fait pas ?"),
        options: [
          B("It writes code faster because it skips building the preview after each change", "Il écrit le code plus vite parce qu'il saute la compilation de la preview"),
          B("It publishes the app to its public address after each answer", "Il publie l'app à son adresse publique après chaque réponse"),
          B("It reasons about the project and plans without editing files", "Il raisonne sur le projet et planifie sans modifier de fichier"),
        ],
        answer: 2,
        why: B("Chat mode is for thinking: questions, comparisons, plans. It reads the project but leaves the files as they are, which makes it the safe place to settle decisions before any code changes.",
          "Le mode discussion sert à réfléchir : questions, comparaisons, plans. Il lit le projet mais laisse les fichiers intacts, ce qui en fait l'endroit sûr pour trancher avant que le code change.") },
      { q: B("Where should you look for how many credits your plan includes?",
          "Où chercher combien de crédits comprend votre offre ?"),
        options: [
          B("In this course, which lists the allowance of every Lovable plan", "Dans ce cours, qui liste les quotas de chaque offre Lovable"),
          B("On the current Lovable pricing page and in your workspace", "Sur la grille tarifaire actuelle de Lovable et dans votre espace"),
          B("In the project knowledge, where Lovable writes the remaining balance", "Dans la connaissance du projet, où Lovable inscrit le solde restant"),
        ],
        answer: 1,
        why: B("Plans and their limits change over time. The official pricing page and your own workspace give the current numbers; a figure copied into a course would soon be wrong.",
          "Les offres et leurs limites changent avec le temps. La grille tarifaire officielle et votre propre espace donnent les chiffres actuels ; un chiffre recopié dans un cours serait vite faux.") },
    ],
  },

  [enrichKey(M1, 'lv-anatomy')]: {
    why: [
      B("A Lovable project follows the conventions of a standard React app. Pages, one per screen, sit in src/pages. Reusable pieces, such as a session card, sit in src/components, and the shadcn/ui building blocks (buttons, inputs, dialogs) in src/components/ui. The file src/App.tsx declares the routes, the link between an address and a page.",
        "Un projet Lovable suit les conventions d'une app React standard. Les pages, une par écran, sont dans src/pages. Les éléments réutilisables, comme une carte de séance, sont dans src/components, et les briques shadcn/ui (champs, fenêtres, listes déroulantes) dans src/components/ui. Le fichier src/App.tsx déclare les routes, c'est-à-dire le lien entre une adresse et une page."),
      B("Knowing this map turns vague prompts into precise ones. Instead of 'the page is broken', you can say 'the route /sessions/:id in App.tsx does not reach SessionPage'. The model then works on the right file, and you can check the change yourself in the code view.",
        "Connaître cette carte transforme des prompts vagues en prompts précis. Au lieu de « la page est cassée », vous pouvez écrire « la route /sessions/:id de App.tsx ne mène pas à SessionPage ». Le modèle travaille alors sur le bon fichier, et vous pouvez vérifier la modification vous-même dans la vue du code."),
      B("Visual edits act on one element selected in the preview: its text, color, spacing or size. They are the right tool for small cosmetic changes, because they change exactly what you selected. A prompt is interpreted, and may rewrite a whole component to change a word.",
        "La retouche visuelle agit sur un élément sélectionné dans la preview : son texte, sa couleur, ses marges ou sa taille. C'est le bon outil pour les petits changements d'apparence, parce qu'elle modifie exactement ce que vous avez sélectionné. Un prompt est interprété, et peut réécrire tout un composant pour changer un mot."),
    ],
    example: {
      context: B("Inès asked for a page per session. The file exists, but opening a session from the home page leads nowhere, and her next prompt only says it does not work.",
        "Inès a demandé une page par séance. Le fichier existe, mais ouvrir une séance depuis l'accueil ne mène nulle part, et son prompt suivant dit seulement que cela ne marche pas."),
      before: B("The session page does not work, fix it.",
        "La page séance ne marche pas, corrige-la."),
      after: B("On the home page of Atelier, each session card should link to its own page.\nThe page file src/pages/SessionPage.tsx exists, but /sessions/3 shows the not found page.\nCheck that src/App.tsx declares a route /sessions/:id pointing to SessionPage, and that the cards link to /sessions/ followed by the session id.\nChange only App.tsx and the session card component if needed. Then tell me which lines you changed.",
        "Sur l'accueil d'Atelier, chaque carte de séance doit mener à sa propre page.\nLe fichier src/pages/SessionPage.tsx existe, mais /sessions/3 affiche la page introuvable.\nVérifie que src/App.tsx déclare une route /sessions/:id qui mène à SessionPage, et que les cartes pointent vers /sessions/ suivi de l'identifiant de la séance.\nModifie seulement App.tsx et, si besoin, le composant de carte de séance. Puis dis-moi quelles lignes tu as changées."),
      takeaway: B("The second prompt names the files, the address and the expected link. The fix touches two files Inès can open and check, instead of a rewrite of the session page that would have hidden the real cause.",
        "Le second prompt nomme les fichiers, l'adresse et le lien attendu. La correction touche deux fichiers qu'Inès peut ouvrir et vérifier, au lieu d'une réécriture de la page séance qui aurait caché la vraie cause."),
    },
    exercise: {
      goal: B("A written map of the Atelier project (pages, components, routes) and one change made by visual edit rather than by prompt.",
        "Une carte écrite du projet Atelier (pages, composants, routes) et une modification faite par retouche visuelle plutôt que par prompt."),
      prompt: B("(Chat mode) Do not edit any file.\nDescribe the structure of Atelier as a table: file, type (page, component, UI block, configuration), what it shows or does.\nThen list every route declared in src/App.tsx with the page it leads to.\nFlag any page file that no route reaches, and any component that is never used.\nI will compare your table with the code view, so mention only files you can see: [FILES YOU WANT EXPLAINED FIRST].",
        "(Mode discussion) Ne modifie aucun fichier.\nDécris la structure d'Atelier sous forme de tableau : fichier, type (page, composant, brique d'interface, configuration), ce qu'il affiche ou fait.\nListe ensuite chaque route déclarée dans src/App.tsx avec la page à laquelle elle mène.\nSignale tout fichier de page qu'aucune route n'atteint, et tout composant jamais utilisé.\nJe comparerai ton tableau avec la vue du code : ne cite que des fichiers que tu vois. Commence par : [FICHIERS À EXPLIQUER EN PREMIER]."),
      check: [
        B("Every file in the table exists in the code view", "Chaque fichier du tableau existe dans la vue du code"),
        B("Each route of App.tsx is matched with a page that you opened", "Chaque route de App.tsx est associée à une page que vous avez ouverte"),
        B("The session page is reachable at an address such as /sessions/1", "La page séance est accessible à une adresse comme /sessions/1"),
        B("One heading or color was changed by visual edit, with no prompt", "Un titre ou une couleur a été changé par retouche visuelle, sans prompt"),
      ],
      bonus: B("After the visual edit, open the code view and find the line that changed. Seeing that a visual edit writes ordinary Tailwind classes and text in a component makes the link between the preview and the code concrete.",
        "Après la retouche visuelle, ouvrez la vue du code et trouvez la ligne modifiée. Constater qu'une retouche visuelle écrit des classes Tailwind et du texte ordinaires dans un composant rend concret le lien entre la preview et le code."),
    },
    more: [
      { q: B("You want to change the color of the booking heading of Atelier, and nothing else. What is the best tool?",
          "Vous voulez changer la couleur du titre de réservation d'Atelier, et rien d'autre. Quel est le meilleur outil ?"),
        options: [
          B("A prompt describing the new color for the whole page", "Un prompt qui décrit la nouvelle couleur pour toute la page"),
          B("A new project knowledge rule about the colors of headings", "Une nouvelle règle de connaissance du projet sur les titres"),
          B("A visual edit on that heading, selected in the preview", "Une retouche visuelle sur ce titre, sélectionné dans la preview"),
        ],
        answer: 2,
        why: B("A visual edit changes exactly the selected element. A prompt is interpreted and may change more; a knowledge rule is for lasting conventions, not for one heading.",
          "La retouche visuelle modifie exactement l'élément sélectionné. Un prompt est interprété et peut changer davantage ; une règle de connaissance sert aux conventions durables, pas à un seul titre.") },
      { q: B("What is the role of the files in src/components/ui in a Lovable project?",
          "Quel est le rôle des fichiers de src/components/ui dans un projet Lovable ?"),
        options: [
          B("They are the shadcn/ui building blocks reused by your pages", "Ce sont les briques shadcn/ui réutilisées par vos pages"),
          B("They hold the database tables and the sample data of the project", "Ils contiennent les tables de la base de données du projet"),
          B("They store the answers that Lovable gave you while in chat mode", "Ils conservent les réponses de Lovable en mode discussion"),
        ],
        answer: 0,
        why: B("shadcn/ui components are copied into the project as source files under src/components/ui. Your pages and components import them; they hold no data and no conversation.",
          "Les composants shadcn/ui sont copiés dans le projet sous forme de fichiers sources, dans src/components/ui. Vos pages et composants les importent ; ils ne contiennent ni données ni conversation.") },
    ],
  },
}

const START_DEEP: Record<string, Deepening> = {
  [deepKey(M1, 'lv-what')]: {
    intro: B("Lovable is often described as a tool that turns a conversation into an app. That is true, and incomplete: it turns a conversation into the source code of a web app, which it builds and shows in a preview. This dojo explains what happens between your prompt and the screen, which stack is generated (React, Vite, TypeScript, Tailwind CSS, shadcn/ui), and where the code lives. You will create the first version of Atelier, the booking app of a small pottery workshop that runs through this whole course, and you will be able to say what Lovable built and where to find it.",
      "On présente souvent Lovable comme un outil qui transforme une conversation en app. C'est vrai, et incomplet : il transforme une conversation en code source d'une app web, qu'il compile et affiche dans une preview. Ce dojo explique ce qui se passe entre votre prompt et l'écran, quelle stack est générée (React, Vite, TypeScript, Tailwind CSS, shadcn/ui) et où vit le code. Vous créerez la première version d'Atelier, l'app de réservation d'un petit atelier de poterie qui sert de fil rouge à tout ce cours, et vous saurez dire ce que Lovable a construit et où le trouver."),
    concepts: [
      { term: B('Prompt to code', 'Du prompt au code'),
        def: B("Each message is turned by a model into changes to project files. The app you see is the result of those files, never of the message itself.",
          "Chaque message est traduit par un modèle en modifications des fichiers du projet. L'app que vous voyez est le résultat de ces fichiers, jamais du message lui-même.") },
      { term: B('Preview', 'Preview'),
        def: B("The running version of your app inside the editor, rebuilt after each change. It shows what the code does now, including what you did not ask for.",
          "La version de l'app qui tourne dans l'éditeur, recompilée après chaque modification. Elle montre ce que fait le code à cet instant, y compris ce que vous n'avez pas demandé.") },
      { term: B('The generated stack', 'La stack générée'),
        def: B("React for the interface, Vite to build and serve it, TypeScript for types, Tailwind CSS for style, shadcn/ui for ready-made components. All are standard, open tools.",
          "React pour l'interface, Vite pour la compiler et la servir, TypeScript pour les types, Tailwind CSS pour le style, shadcn/ui pour des composants prêts à l'emploi. Tous sont des outils standard et ouverts.") },
      { term: B('Code view', 'Vue du code'),
        def: B("The part of the editor where you read the files of the project. It is where you check what a prompt really changed.",
          "La partie de l'éditeur où vous lisez les fichiers du projet. C'est là que vous vérifiez ce qu'un prompt a réellement modifié.") },
    ],
    walkthrough: {
      title: B("Inès creates the first version of Atelier, her pottery workshop booking app, and checks what was built.",
        "Inès crée la première version d'Atelier, l'app de réservation de son atelier de poterie, et vérifie ce qui a été construit."),
      steps: [
        B("She writes a short prompt naming two pages, the session list and the session page, and asks for sample data without a database. Why: a first version with fake data shows the structure before any backend decision.",
          "Elle écrit un court prompt qui nomme deux pages, la liste des séances et la page séance, et demande des données d'exemple sans base. Pourquoi : une première version aux données fictives montre la structure avant toute décision de backend."),
        B("The preview appears with six sample sessions. She opens one, then returns to the list. Why: she tests the app as a visitor would, before reading any code.",
          "La preview apparaît avec six séances d'exemple. Elle en ouvre une, puis revient à la liste. Pourquoi : elle teste l'app comme le ferait un visiteur, avant de lire le code."),
        B("She opens the code view and reads package.json: react, vite, tailwindcss and several shadcn/ui dependencies are listed. Why: the dependencies tell her the stack with certainty, without trusting a description.",
          "Elle ouvre la vue du code et lit package.json : react, vite, tailwindcss et plusieurs dépendances liées à shadcn/ui y figurent. Pourquoi : les dépendances lui donnent la stack avec certitude, sans se fier à une description."),
        B("She finds the sample sessions written directly in a file under src. Why: she now knows that the data is temporary, and that the next step, a real database, will replace this file.",
          "Elle trouve les séances d'exemple écrites directement dans un fichier de src. Pourquoi : elle sait désormais que les données sont provisoires, et que l'étape suivante, une vraie base, remplacera ce fichier."),
        B("She writes three notes: the stack, the pages and their files, the choices the model made alone (a seats counter, a color palette). Why: these notes become the starting point of her project knowledge in the next city.",
          "Elle rédige trois notes : la stack, les pages et leurs fichiers, les choix faits seul par le modèle (un compteur de places, une palette). Pourquoi : ces notes deviendront le point de départ de la connaissance du projet, dans la cité suivante."),
      ],
    },
    mistakes: [
      { wrong: B("Believing the app is stored only inside Lovable, in a form nobody else can use.",
          "Croire que l'app n'existe que dans Lovable, sous une forme que personne d'autre ne peut utiliser."),
        fix: B("Remember that the project is ordinary source code. Read it in the code view, and plan to sync it to GitHub so that it is yours outside the editor too.",
          "Retenez que le projet est du code source ordinaire. Lisez-le dans la vue du code, et prévoyez de le synchroniser avec GitHub pour qu'il vous appartienne aussi hors de l'éditeur.") },
      { wrong: B("Judging the first version only by how it looks in the preview.",
          "Juger la première version uniquement sur son apparence dans la preview."),
        fix: B("Use it as a visitor would, then open the code view to see where the data and the pages are. Looks say little about structure.",
          "Utilisez-la comme un visiteur, puis ouvrez la vue du code pour voir où sont les données et les pages. L'apparence dit peu de chose de la structure.") },
      { wrong: B("Asking for everything in the first prompt: accounts, payments, admin, emails.",
          "Tout demander dès le premier prompt : comptes, paiement, administration, emails."),
        fix: B("Start with the pages and sample data. Each layer, backend, accounts, dashboard, comes later in its own request, when you can check it.",
          "Commencez par les pages et des données d'exemple. Chaque couche, backend, comptes, tableau de bord, viendra ensuite dans sa propre demande, quand vous pourrez la vérifier.") },
    ],
    recap: [
      B("Lovable turns your messages into the source code of a real web app.", "Lovable transforme vos messages en code source d'une vraie app web."),
      B("The stack is React, Vite, TypeScript, Tailwind CSS and shadcn/ui, all standard tools.", "La stack est React, Vite, TypeScript, Tailwind CSS et shadcn/ui, tous des outils standard."),
      B("The preview shows what the code does, including choices you never asked for.", "La preview montre ce que fait le code, y compris des choix que vous n'avez pas demandés."),
      B("The code view and package.json tell you what was built, with certainty.", "La vue du code et package.json disent avec certitude ce qui a été construit."),
    ],
    further: B("Read the official Lovable documentation page that describes the generated stack and the project structure, and compare it with your own Atelier project. Note any difference: the documentation describes the general case, your code view describes your case.",
      "Lisez la page de la documentation officielle de Lovable qui décrit la stack générée et la structure d'un projet, et comparez-la avec votre projet Atelier. Notez toute différence : la documentation décrit le cas général, votre vue du code décrit le vôtre."),
    more: [
      { q: B("Which file tells you with certainty which libraries the Atelier project uses?",
          "Quel fichier vous dit avec certitude quelles bibliothèques utilise le projet Atelier ?"),
        options: [
          B("The last answer Lovable wrote in the conversation", "La dernière réponse écrite par Lovable dans la conversation"),
          B("package.json, which lists the dependencies", "package.json, qui liste les dépendances"),
          B("The preview, where each library leaves a visible mark", "La preview, où chaque bibliothèque laisse une trace visible"),
        ],
        answer: 1,
        why: B("package.json is the list the build actually uses. A chat answer is a description that may be wrong, and the preview shows the result, not the tools behind it.",
          "package.json est la liste que la compilation utilise réellement. Une réponse de la conversation est une description qui peut être fausse, et la preview montre le résultat, pas les outils qui le produisent.") },
      { q: B("Why start Atelier with sample data written in the code rather than with a database?",
          "Pourquoi commencer Atelier avec des données d'exemple écrites dans le code plutôt qu'avec une base ?"),
        options: [
          B("Because Lovable cannot connect a database to a new project", "Parce que Lovable ne peut pas brancher de base sur un nouveau projet"),
          B("Because sample data is safer to publish to the public", "Parce que des données d'exemple sont plus sûres à publier"),
          B("To see and correct the structure before backend choices", "Pour voir et corriger la structure avant les choix de backend"),
        ],
        answer: 2,
        why: B("Pages, fields and navigation are cheap to change while the data is fake. Once tables, accounts and security rules exist, every structural change touches more layers.",
          "Pages, champs et navigation se changent à peu de frais tant que les données sont fictives. Une fois les tables, les comptes et les règles de sécurité en place, chaque changement de structure touche plus de couches.") },
    ],
  },

  [deepKey(M1, 'lv-modes')]: {
    intro: B("Talking to Lovable is not one gesture but two. You can think with it, in chat mode, where it reads the project and answers without editing files; or you can let it act, in the default mode, where each message may change code. This dojo explains when to use each, how credits are drawn by your messages, and why a small, precise request costs less and works better than a large one. You will plan the booking form of Atelier before building it, and you will be able to keep each change small enough to check in a minute.",
      "Parler à Lovable n'est pas un geste unique, mais deux. Vous pouvez réfléchir avec lui, en mode discussion, où il lit le projet et répond sans modifier de fichier ; ou le laisser agir, dans le mode par défaut, où chaque message peut changer le code. Ce dojo explique quand utiliser l'un ou l'autre, comment vos messages consomment des crédits, et pourquoi une demande petite et précise coûte moins et fonctionne mieux qu'une grande. Vous planifierez le formulaire de réservation d'Atelier avant de le construire, et vous saurez garder chaque changement assez petit pour le vérifier en une minute."),
    concepts: [
      { term: B('Chat mode', 'Mode discussion'),
        def: B("A way of talking to Lovable where it reads and reasons about the project but does not edit files. It is used to ask questions, compare options and get a plan.",
          "Une manière de parler à Lovable où il lit le projet et raisonne dessus sans modifier de fichier. On l'utilise pour poser des questions, comparer des options et obtenir un plan.") },
      { term: B('Default mode', 'Mode par défaut'),
        def: B("The mode where each message can change the code of the project. Every change creates a new version you can return to.",
          "Le mode où chaque message peut modifier le code du projet. Chaque modification crée une nouvelle version à laquelle vous pouvez revenir.") },
      { term: B('Credits', 'Crédits'),
        def: B("The unit in which Lovable counts usage. Their amount and the way messages draw on them depend on your plan and change over time: check the current pricing page.",
          "L'unité dans laquelle Lovable compte l'usage. Leur volume et la manière dont les messages les consomment dépendent de votre offre et évoluent : consultez la grille tarifaire actuelle.") },
      { term: B('Scope of a request', "Périmètre d'une demande"),
        def: B("What one message asks to change. A narrow scope (one goal, few files) is easier for the model to get right and for you to check.",
          "Ce qu'un message demande de modifier. Un périmètre étroit, un objectif et peu de fichiers, est plus facile à réussir pour le modèle et à vérifier pour vous.") },
    ],
    walkthrough: {
      title: B("Inès adds the booking form to the session page of Atelier, in two steps: a plan, then one edit.",
        "Inès ajoute le formulaire de réservation à la page séance d'Atelier, en deux temps : un plan, puis une modification."),
      steps: [
        B("She switches to chat mode and asks how Lovable would add the form: name, email, one to four seats. Why: nothing is changed yet, so she can correct freely.",
          "Elle passe en mode discussion et demande comment Lovable ajouterait le formulaire : nom, email, de une à quatre places. Pourquoi : rien n'est encore modifié, elle peut corriger librement."),
        B("The plan proposes to also create a confirmation page and to store bookings in the browser. She refuses both: the confirmation will be a message, and storage will come with the database. Why: each refused extra is a file that will not need checking.",
          "Le plan propose aussi une page de confirmation et un stockage des réservations dans le navigateur. Elle refuse les deux : la confirmation sera un message, et le stockage viendra avec la base. Pourquoi : chaque ajout refusé est un fichier de moins à vérifier."),
        B("She asks what the plan leaves open. Lovable asks what happens when a session is full. She answers: the form is replaced by the words « Complet ». Why: an open decision answered now is a bug avoided later.",
          "Elle demande ce que le plan laisse ouvert. Lovable demande ce qui se passe quand une séance est pleine. Elle répond : le formulaire est remplacé par la mention « Complet ». Pourquoi : une décision tranchée maintenant est un bug évité plus tard."),
        B("She returns to the default mode and sends one message: implement the agreed plan, and only it. Why: a single goal means a single version to check, and a single version to restore if needed.",
          "Elle revient au mode par défaut et envoie un message : mettre en oeuvre le plan convenu, et lui seul. Pourquoi : un seul objectif signifie une seule version à vérifier, et une seule à restaurer au besoin."),
        B("She tests the form in the preview with a full session and with a valid booking, then notes the credits used. Why: testing the decided cases confirms the plan was followed, and the note helps her estimate future requests.",
          "Elle teste le formulaire dans la preview avec une séance pleine et une réservation valide, puis note les crédits consommés. Pourquoi : tester les cas décidés confirme que le plan a été suivi, et la note l'aide à estimer ses prochaines demandes."),
      ],
    },
    mistakes: [
      { wrong: B("Using the default mode to ask a question, and finding files changed in response.",
          "Utiliser le mode par défaut pour poser une question, et découvrir des fichiers modifiés en réponse."),
        fix: B("Ask questions and request plans in chat mode. Switch to the default mode only when you know what you want built.",
          "Posez les questions et demandez les plans en mode discussion. Passez au mode par défaut seulement quand vous savez ce que vous voulez construire.") },
      { wrong: B("Packing several features into one message to save credits.",
          "Regrouper plusieurs fonctionnalités dans un message pour économiser des crédits."),
        fix: B("Send one goal per message. A large request that fails costs the request, the restore and the retry; small requests rarely need redoing.",
          "Envoyez un objectif par message. Une grande demande qui échoue coûte la demande, la restauration et le nouvel essai ; les petites demandes se refont rarement.") },
      { wrong: B("Quoting a credit figure read in a forum as the rule for your plan.",
          "Prendre un chiffre de crédits lu sur un forum comme règle de votre offre."),
        fix: B("Read the current pricing page and the usage shown in your workspace. Plans change, and only those sources reflect yours.",
          "Lisez la grille tarifaire actuelle et la consommation affichée dans votre espace. Les offres changent, et seules ces sources reflètent la vôtre.") },
    ],
    recap: [
      B("Chat mode is for thinking: questions, options and plans, without editing files.", "Le mode discussion sert à réfléchir : questions, options et plans, sans modifier de fichier."),
      B("The default mode edits code, and each change creates a version you can restore.", "Le mode par défaut modifie le code, et chaque changement crée une version restaurable."),
      B("One message, one goal: it costs less, works better and is easy to check.", "Un message, un objectif : cela coûte moins, fonctionne mieux et se vérifie facilement."),
      B("Credit amounts depend on your plan: the current pricing page is the only reference.", "Le volume de crédits dépend de votre offre : la grille tarifaire actuelle est la seule référence."),
    ],
    further: B("For your next three requests on Atelier, start each one with a plan in chat mode, even when the change looks obvious. Note how often the plan revealed a decision you had not made: that count tells you how much planning is worth on your own project.",
      "Pour vos trois prochaines demandes sur Atelier, commencez chacune par un plan en mode discussion, même quand le changement paraît évident. Notez combien de fois le plan a révélé une décision que vous n'aviez pas prise : ce compte vous dit ce que vaut la planification sur votre projet."),
    more: [
      { q: B("The plan for the booking form proposes three extra files you did not ask for. What do you do?",
          "Le plan du formulaire de réservation propose trois fichiers supplémentaires non demandés. Que faites-vous ?"),
        options: [
          B("Accept them: the model knows better what the form requires", "Vous les acceptez : le modèle sait mieux ce que demande le formulaire"),
          B("Ask why each is needed, keep only what serves your goal", "Vous demandez à quoi sert chacun et ne gardez que l'utile"),
          B("Switch to the default mode at once so the plan cannot grow", "Vous passez tout de suite au mode par défaut pour figer le plan"),
        ],
        answer: 1,
        why: B("Extras in a plan are decisions taken for you. Asking their purpose costs one chat message; each one you refuse is a file you will not have to check or debug.",
          "Les ajouts d'un plan sont des décisions prises à votre place. Demander leur utilité coûte un message ; chaque ajout refusé est un fichier que vous n'aurez ni à vérifier ni à déboguer.") },
      { q: B("Why does a small request usually give better code than a large one?",
          "Pourquoi une petite demande donne-t-elle en général un meilleur code qu'une grande ?"),
        options: [
          B("Because the model has fewer decisions to guess and you can check it", "Parce que le modèle a moins de décisions à deviner et que vous vérifiez"),
          B("Because small requests are sent to a more capable model in the background", "Parce que les petites demandes utilisent un modèle plus puissant"),
          B("Because large requests are refused once they exceed a word limit", "Parce que les grandes demandes sont refusées au-delà d'un nombre de mots"),
        ],
        answer: 0,
        why: B("A narrow request leaves little to guess and touches few files. You can check the result in the preview right away, and correct it before the next change builds on top of it.",
          "Une demande étroite laisse peu à deviner et touche peu de fichiers. Vous vérifiez le résultat dans la preview aussitôt, et le corrigez avant que le changement suivant ne s'appuie dessus.") },
    ],
  },

  [deepKey(M1, 'lv-anatomy')]: {
    intro: B("To steer Lovable well, you need to know what you are steering. A Lovable project has the anatomy of a standard React app: pages in src/pages, reusable components in src/components, shadcn/ui blocks in src/components/ui, routes in src/App.tsx, global styles in src/index.css and the Tailwind configuration. This dojo teaches you to read that map in the code view, to name the right file in your prompts, and to recognise when a visual edit on the preview is better than a prompt. You will add the route of a session page to Atelier and make your first visual edit.",
      "Pour bien diriger Lovable, il faut savoir ce que l'on dirige. Un projet Lovable a l'anatomie d'une app React standard : pages dans src/pages, composants réutilisables dans src/components, briques shadcn/ui dans src/components/ui, routes dans src/App.tsx, styles globaux dans src/index.css et la configuration de Tailwind. Ce dojo vous apprend à lire cette carte dans la vue du code, à nommer le bon fichier dans vos prompts, et à reconnaître quand une retouche visuelle sur la preview vaut mieux qu'un prompt. Vous ajouterez la route d'une page séance à Atelier et ferez votre première retouche visuelle."),
    concepts: [
      { term: B('Page', 'Page'),
        def: B("A component that represents a whole screen, such as the session list or a session page. In a Lovable project, pages live in src/pages.",
          "Un composant qui représente un écran entier, comme la liste des séances ou une page séance. Dans un projet Lovable, les pages sont dans src/pages.") },
      { term: B('Component', 'Composant'),
        def: B("A reusable piece of interface, such as a session card or a booking form, written once and used in several pages.",
          "Un élément d'interface réutilisable, comme une carte de séance ou un formulaire de réservation, écrit une fois et utilisé dans plusieurs pages.") },
      { term: B('Route', 'Route'),
        def: B("The link between an address and a page, for example /sessions/:id and the session page. Routes are declared in src/App.tsx; :id is a variable part of the address.",
          "Le lien entre une adresse et une page, par exemple /sessions/:id et la page séance. Les routes sont déclarées dans src/App.tsx ; :id est une partie variable de l'adresse.") },
      { term: B('Visual edit', 'Retouche visuelle'),
        def: B("A change made by selecting an element in the preview and adjusting its text, color, spacing or size directly, without writing a prompt.",
          "Une modification faite en sélectionnant un élément dans la preview et en ajustant directement son texte, sa couleur, ses marges ou sa taille, sans écrire de prompt.") },
    ],
    walkthrough: {
      title: B("Inès maps her Atelier project, fixes the route to the session page, and adjusts the home heading by visual edit.",
        "Inès cartographie son projet Atelier, répare la route vers la page séance et ajuste le titre d'accueil par retouche visuelle."),
      steps: [
        B("She opens the code view and lists src/pages: Index.tsx and NotFound.tsx, plus the new SessionPage.tsx. Why: she needs to know which screens exist before asking for anything.",
          "Elle ouvre la vue du code et liste src/pages : Index.tsx et NotFound.tsx, plus le nouveau SessionPage.tsx. Pourquoi : elle doit savoir quels écrans existent avant de demander quoi que ce soit."),
        B("She reads src/App.tsx and sees two routes: / and a catch-all for unknown addresses. No route leads to SessionPage. Why: this explains why opening a session showed the not found page.",
          "Elle lit src/App.tsx et voit deux routes : / et une route attrape-tout pour les adresses inconnues. Aucune route ne mène à SessionPage. Pourquoi : cela explique pourquoi ouvrir une séance affichait la page introuvable."),
        B("She asks Lovable to add the route /sessions/:id to SessionPage, before the catch-all, and to make each session card link to it. Why: naming the file and the address limits the change to what is broken.",
          "Elle demande à Lovable d'ajouter la route /sessions/:id vers SessionPage, avant la route attrape-tout, et de faire pointer chaque carte de séance vers elle. Pourquoi : nommer le fichier et l'adresse limite la modification à ce qui est cassé."),
        B("She opens /sessions/2 in the preview, then checks App.tsx: one new line, in the right place. Why: verifying in both the preview and the code confirms the fix and what it touched.",
          "Elle ouvre /sessions/2 dans la preview, puis vérifie App.tsx : une ligne de plus, au bon endroit. Pourquoi : vérifier à la fois dans la preview et dans le code confirme la correction et ce qu'elle a touché."),
        B("She selects the home heading in the preview and changes its text to « Les prochaines séances » with a larger size, by visual edit. Why: a precise cosmetic change needs no interpretation, so no prompt.",
          "Elle sélectionne le titre d'accueil dans la preview et change son texte en « Les prochaines séances », en plus grand, par retouche visuelle. Pourquoi : un changement d'apparence précis n'a besoin d'aucune interprétation, donc d'aucun prompt."),
      ],
    },
    mistakes: [
      { wrong: B("Writing 'the page is broken' without saying which page, which address or what happens.",
          "Écrire « la page est cassée » sans dire quelle page, quelle adresse ni ce qui se passe."),
        fix: B("Name the address, the file and the observed behaviour: '/sessions/3 shows the not found page; check the route in App.tsx'.",
          "Nommez l'adresse, le fichier et le comportement observé : « /sessions/3 affiche la page introuvable ; vérifie la route dans App.tsx ».") },
      { wrong: B("Using prompts for every small change of wording or color.",
          "Passer par des prompts pour chaque petit changement de texte ou de couleur."),
        fix: B("Use a visual edit when you can point at the element and know the result you want. Keep prompts for changes that need reasoning.",
          "Utilisez la retouche visuelle quand vous pouvez désigner l'élément et savez le résultat voulu. Gardez les prompts pour les changements qui demandent un raisonnement.") },
      { wrong: B("Editing files in src/components/ui by hand to change one page.",
          "Modifier à la main les fichiers de src/components/ui pour changer une seule page."),
        fix: B("These blocks are shared by every page. Change the page or the component that uses them, unless you really want the change everywhere.",
          "Ces briques sont partagées par toutes les pages. Modifiez la page ou le composant qui les utilise, sauf si vous voulez vraiment le changement partout.") },
    ],
    recap: [
      B("Pages are in src/pages, components in src/components, shadcn/ui blocks in src/components/ui.", "Les pages sont dans src/pages, les composants dans src/components, les briques shadcn/ui dans src/components/ui."),
      B("Routes in src/App.tsx link each address to a page; a page without a route is unreachable.", "Les routes de src/App.tsx relient chaque adresse à une page ; une page sans route est inaccessible."),
      B("Naming the file and the address in a prompt keeps the change small and checkable.", "Nommer le fichier et l'adresse dans un prompt garde la modification petite et vérifiable."),
      B("A visual edit is the right tool for a precise cosmetic change on one element.", "La retouche visuelle est le bon outil pour un changement d'apparence précis sur un élément."),
    ],
    further: B("Open the React Router documentation page on routes with parameters and read how /sessions/:id gives the page access to the id. Then ask Lovable, in chat mode, to show you where SessionPage reads that id: you will understand how one page displays many sessions.",
      "Ouvrez la page de la documentation de React Router consacrée aux routes à paramètres et lisez comment /sessions/:id donne l'identifiant à la page. Demandez ensuite à Lovable, en mode discussion, de vous montrer où SessionPage lit cet identifiant : vous comprendrez comment une seule page affiche de nombreuses séances."),
    more: [
      { q: B("Why must the route /sessions/:id be declared before the catch-all route in App.tsx?",
          "Pourquoi la route /sessions/:id doit-elle être déclarée avant la route attrape-tout dans App.tsx ?"),
        options: [
          B("Because the catch-all would otherwise answer first for that address", "Parce que la route attrape-tout répondrait sinon en premier"),
          B("Because Vite compiles routes in alphabetical order of their names", "Parce que Vite compile les routes dans l'ordre alphabétique"),
          B("Because TypeScript forbids declaring a route with a parameter after another one", "Parce que TypeScript interdit une route à paramètre après une autre"),
        ],
        answer: 0,
        why: B("The catch-all exists to answer any unknown address. Keeping it last ensures that specific routes, like the session page, are matched before it; Lovable projects place it at the end for that reason.",
          "La route attrape-tout répond à toute adresse inconnue. La garder en dernier garantit que les routes précises, comme la page séance, sont reconnues avant elle ; les projets Lovable la placent à la fin pour cette raison.") },
      { q: B("You want every session card of Atelier to have softer corners. Which approach fits best?",
          "Vous voulez des coins plus arrondis sur toutes les cartes de séance d'Atelier. Quelle approche convient le mieux ?"),
        options: [
          B("A visual edit on each card of the home page, one by one", "Une retouche visuelle sur chaque carte de l'accueil, une à une"),
          B("A new rule in the project knowledge, then waiting for the next prompt", "Une règle dans la connaissance du projet, puis attendre le prochain prompt"),
          B("A precise prompt on the session card component, then a check", "Un prompt précis sur le composant de carte, puis une vérification"),
        ],
        answer: 2,
        why: B("The change concerns one component used many times, so the component is the right target. A visual edit acts on one instance; a knowledge rule guides future work but changes no existing code.",
          "Le changement concerne un composant utilisé de nombreuses fois : c'est donc lui qu'il faut viser. Une retouche visuelle agit sur une occurrence ; une règle de connaissance oriente le travail futur sans modifier le code existant.") },
    ],
  },
}

/* ================================================================== */
/* LES CITÉS DU COURS                                                  */
/* ================================================================== */

const MODULES: Module[] = [
  {
    id: M1, track: 'course', glyph: 'diamond', tint: '#a855f7', at: [12, 82], levels: START,
    title: B('Understand Lovable', 'Comprendre Lovable'),
    blurb: B('What Lovable generates and how, the two ways of talking to it, and the anatomy of a project.',
      'Ce que Lovable génère et comment, les deux façons de lui parler, et l\'anatomie d\'un projet.'),
  },
]

export const LOVABLE: CoursePart = {
  modules: MODULES,
  enrich: { ...START_ENRICH },
  deep: { ...START_DEEP },
}
