import { chromium } from 'playwright'
const OUT = process.env.SCRATCH || '.'
const browser = await chromium.launch({ ...(process.env.PW_CHROMIUM ? { executablePath: process.env.PW_CHROMIUM } : {}), args: ['--no-sandbox'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errs = []
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()) })
page.on('pageerror', (e) => errs.push('PAGEERR: ' + e.message))
await page.goto('http://localhost:4173/', { waitUntil: 'load' })
await page.waitForTimeout(1000)
console.log('agents', await page.locator('.agent').count(), 'furn', await page.locator('.furn').count())
await page.screenshot({ path: `${OUT}/kw-full.png` })
await page.locator('.agent', { hasText: 'Mia' }).click().catch(()=>{})
await page.waitForTimeout(400)
await page.screenshot({ path: `${OUT}/kw-selected.png` })
const box = await page.locator('.agent', { hasText: 'Mia' }).boundingBox().catch(()=>null)
if (box) await page.screenshot({ path: `${OUT}/kw-char.png`, clip:{ x: box.x-50, y: box.y-40, width: 200, height: 200 } })
const clean = errs.filter((e) => !/fonts\.g|ERR_CONNECTION|xumm|Failed to load resource|40\d|429/.test(e))
console.log('console errors:', clean.length ? clean : 'none')
const m = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true })
await m.goto('http://localhost:4173/', { waitUntil: 'load' }); await m.waitForTimeout(800)
const ov = await m.evaluate(() => ({ w: document.body.scrollWidth, iw: window.innerWidth }))
console.log('mobile overflow', ov.w, 'vs', ov.iw, ov.w > ov.iw+1 ? 'OVERFLOW':'ok')
await m.screenshot({ path: `${OUT}/kw-mobile.png` })
await browser.close(); console.log('DONE')
