// LES TEXTES DE L'INTERFACE SCOLAIRE · l'école s'affiche en français (demandé :
// « fais juste la version française », voir useS dans SchoolPages). L'anglais
// est gardé à côté, sans être affiché, sauf pour l'onglet des formations IA.
import { B } from '../data/bilingual'

export const ST = {
  // l'accueil
  title: B('School, from A to Z', 'L\'école, de A à Z'),
  lead: B('Every subject of the French curriculum, from 6e to Terminale: a course, a key-points sheet, worked examples, exercises with corrections, a game and a quiz in every lesson. A parent validates each lesson, and the brevet and the bac have their mock exams.',
    'Toutes les matières du programme, de la 6e à la Terminale : dans chaque leçon, un cours, une fiche de l\'essentiel, un exemple corrigé, des exercices corrigés, un jeu et un quiz. Un parent valide chaque leçon, et le brevet comme le bac ont leurs épreuves blanches.'),
  tabAi: B('AI courses', 'Formations IA'),
  tabSchool: B('School (collège, lycée)', 'École (collège, lycée)'),
  college: B('Collège', 'Collège'),
  lycee: B('Lycée', 'Lycée'),
  pickGrade: B('Choose your class', 'Choisissez votre classe'),
  exams: B('Prepare for the exams', 'Préparer les examens'),
  examsLead: B('The format of each paper, the chapters to revise, and timed mock exams.', 'Le format de chaque épreuve, les chapitres à réviser, et des épreuves blanches chronométrées.'),
  iaCard: B('Learning with AI', 'Apprendre avec l\'IA'),
  iaLead: B('How to use AI at school to learn better, without losing good study habits.', 'Comment utiliser l\'IA à l\'école pour mieux apprendre, sans perdre les bonnes méthodes de travail.'),
  parents: B('Parents\' space', 'Espace parents'),
  parentsLead: B('Create the 4-digit parent code, follow the progress and validate each lesson.', 'Créez le code parent à 4 chiffres, suivez la progression et validez chaque leçon.'),
  parentsReady: B('Parent code set for', 'Code parent créé pour'),
  freeBeta: B('Free during the beta', 'Gratuit pendant la bêta'),
  // la classe et l'unité
  subjects: B('Subjects', 'Matières'),
  lessons: B('lessons', 'leçons'),
  written: B('written', 'rédigées'),
  validated: B('validated', 'validées'),
  soon: B('Coming soon', 'Bientôt'),
  soonLead: B('The plan follows the official curriculum; the lessons of this subject are being written.', 'Le plan suit le programme officiel ; les leçons de cette matière sont en cours de rédaction.'),
  chapter: B('Chapter', 'Chapitre'),
  programme: B('Curriculum', 'Programme'),
  reference: B('Official reference', 'Référence officielle'),
  start: B('Start', 'Commencer'),
  resume: B('Continue', 'Continuer'),
  examLink: B('Prepare for the exam', 'Préparer l\'examen'),
  loading: B('Loading...', 'Chargement...'),
  notFound: B('This page does not exist.', 'Cette page n\'existe pas.'),
  back: B('Back', 'Retour'),
  // la leçon
  objectives: B('You will be able to', 'Vous saurez'),
  course: B('The course', 'Le cours'),
  keyPoints: B('Key points to remember', 'L\'essentiel à retenir'),
  example: B('Worked example', 'Exemple corrigé'),
  showCorrection: B('Show the correction', 'Voir la correction'),
  hideCorrection: B('Hide the correction', 'Masquer la correction'),
  exercises: B('Exercises', 'Exercices'),
  level1: B('Application', 'Application'),
  level2: B('Practice', 'Entraînement'),
  level3: B('Exam style', 'Type examen'),
  hint: B('Hint', 'Indice'),
  didIt: B('I got it right', 'J\'ai réussi'),
  toReview: B('To review', 'À revoir'),
  selfCheck: B('After reading the correction, how did it go?', 'Après avoir lu la correction, comment cela s\'est-il passé ?'),
  game: B('The game', 'Le jeu'),
  replay: B('Play again', 'Rejouer'),
  trap: B('The common mistake', 'L\'erreur fréquente'),
  method: B('Method', 'Méthode'),
  quiz: B('Check yourself', 'Vérifiez-vous'),
  question: B('Question', 'Question'),
  retry: B('Try the quiz again', 'Recommencer le quiz'),
  quizResult: B('right answers', 'bonnes réponses'),
  // la validation
  validation: B('Parent validation', 'Validation par un parent'),
  needQuiz: B('Quiz passed (60 % or more)', 'Quiz réussi (60 % ou plus)'),
  needGame: B('Game completed', 'Jeu réussi'),
  needEx: B('The three exercises self-checked', 'Les trois exercices autoévalués'),
  askParent: B('Ask a parent to enter their code to validate this lesson.', 'Demandez à un parent de saisir son code pour valider cette leçon.'),
  noParent: B('A parent must first create their code in the parents\' space.', 'Un parent doit d\'abord créer son code dans l\'Espace parents.'),
  parentCode: B('Parent code', 'Code du parent'),
  wrongCode: B('That code is not the right one.', 'Ce code n\'est pas le bon.'),
  locked: B('Too many attempts: try again in', 'Trop d\'essais : réessayez dans'),
  seconds: B('seconds', 'secondes'),
  validatedOn: B('Lesson validated by a parent on', 'Leçon validée par un parent le'),
  nextLesson: B('Next lesson', 'Leçon suivante'),
  // les jeux
  pairsWin: B('All the pairs are matched.', 'Toutes les paires sont reliées.'),
  orderCheck: B('Check the order', 'Vérifier l\'ordre'),
  orderWin: B('This is the right order.', 'C\'est le bon ordre.'),
  orderTry: B('The items in red are not in their place: move them and check again.', 'Les éléments en rouge ne sont pas à leur place : déplacez-les et vérifiez de nouveau.'),
  up: B('Move up', 'Monter'),
  down: B('Move down', 'Descendre'),
  isTrue: B('True', 'Vrai'),
  isFalse: B('False', 'Faux'),
  tfWin: B('No mistakes.', 'Sans faute.'),
  tfTry: B('right answers. Read the explanations, then play again to complete the game.', 'bonnes réponses. Relisez les explications, puis rejouez pour réussir le jeu.'),
  // l'espace parents
  setupH: B('Create the parent code', 'Créer le code parent'),
  setupLead: B('The code stays on this device: only a fingerprint of it is kept, never the code itself. Your child cannot validate a lesson without it.', 'Le code reste sur cet appareil : seule une empreinte en est gardée, jamais le code lui-même. Votre enfant ne peut pas valider une leçon sans lui.'),
  childName: B('Your child\'s first name', 'Le prénom de votre enfant'),
  childGrade: B('Class', 'Classe'),
  code: B('4-digit code', 'Code à 4 chiffres'),
  codeAgain: B('Type the code again', 'Saisissez le code une seconde fois'),
  codeMismatch: B('The two codes are different.', 'Les deux codes sont différents.'),
  create: B('Create the code', 'Créer le code'),
  dashboard: B('Progress', 'Progression'),
  toValidate: B('Lessons waiting for your validation', 'Leçons en attente de votre validation'),
  noneToValidate: B('No lesson is waiting for validation.', 'Aucune leçon n\'attend de validation.'),
  validate: B('Validate', 'Valider'),
  recent: B('Recently validated', 'Validées récemment'),
  mocks: B('Mock exams', 'Épreuves blanches'),
  manage: B('Settings', 'Réglages'),
  changeCode: B('Change the code', 'Changer le code'),
  oldCode: B('Current code', 'Code actuel'),
  newCode: B('New code', 'Nouveau code'),
  reset: B('Reset all school progress', 'Remettre à zéro toute la progression scolaire'),
  resetDone: B('School progress has been reset.', 'La progression scolaire a été remise à zéro.'),
  codeFirst: B('Choose the 4-digit code', 'Choisissez le code à 4 chiffres'),
  next: B('Next', 'Continuer'),
  cancel: B('Cancel', 'Annuler'),
  childOf: B('Progress of', 'Progression de'),
  unitsStarted: B('Subjects in progress', 'Matières commencées'),
  noProgress: B('No lesson started yet. Progress appears here as soon as your child begins a lesson.', 'Aucune leçon commencée pour l\'instant. La progression s\'affiche ici dès que votre enfant commence une leçon.'),
  started: B('started', 'commencées'),
  waiting: B('waiting', 'en attente'),
  quizScore: B('Quiz', 'Quiz'),
  open: B('Open', 'Ouvrir'),
  validateWith: B('Enter your code to validate', 'Saisissez votre code pour valider'),
  noMocks: B('No mock exam taken yet.', 'Aucune épreuve blanche passée pour l\'instant.'),
  mockValidated: B('Validated', 'Validée'),
  codeChanged: B('The code has been changed.', 'Le code a été changé.'),
  resetWarn: B('This erases every lesson, validation and mock exam, and the code itself. Enter the code to confirm.', 'Cela efface toutes les leçons, validations et épreuves blanches, ainsi que le code lui-même. Saisissez le code pour confirmer.'),
  deviceNote: B('Progress is kept in this browser. If it is cleared, progress and code are cleared too.', 'La progression est gardée dans ce navigateur. S\'il est effacé, la progression et le code le sont aussi.'),
  // les examens
  epreuves: B('The papers', 'Les épreuves'),
  duration: B('Duration', 'Durée'),
  coefficient: B('Coefficient', 'Coefficient'),
  revise: B('Revise', 'Réviser'),
  mock: B('Take a mock exam', 'Passer une épreuve blanche'),
  mockSoon: B('The mock exam opens once the lessons of this paper are written.', 'L\'épreuve blanche ouvre dès que les leçons de cette épreuve sont rédigées.'),
  sources: B('Sources (check the official texts)', 'Sources (vérifiez les textes officiels)'),
  minutes: B('min', 'min'),
  mockIntro: B('Timed like the real paper. Part A: questions; part B: exam-style exercises, corrected and self-assessed at the end.', 'Chronométrée comme l\'épreuve réelle. Partie A : des questions ; partie B : des exercices type examen, corrigés et autoévalués à la fin.'),
  begin: B('Begin', 'Commencer l\'épreuve'),
  timeLeft: B('Time left', 'Temps restant'),
  partA: B('Part A · Questions', 'Partie A · Questions'),
  partB: B('Part B · Exercises', 'Partie B · Exercices'),
  finish: B('Finish and correct', 'Terminer et corriger'),
  full: B('Fully right', 'Réussi'),
  partial: B('Partly right', 'En partie'),
  wrong: B('Missed', 'Raté'),
  score: B('Score', 'Note'),
  saveScore: B('Record the score', 'Enregistrer la note'),
  questionsN: B('questions', 'questions'),
  exercisesN: B('exam-style exercises', 'exercices type examen'),
  realPaper: B('Real paper', 'Épreuve réelle'),
  mockTime: B('Mock exam', 'Épreuve blanche'),
  timeUp: B('Time is up: here is the correction.', 'Le temps est écoulé : voici la correction.'),
  scoreRule: B('Part A counts for 8 points, part B for 12 points (fully right: all the points; partly right: half).', 'La partie A compte pour 8 points, la partie B pour 12 points (réussi : tous les points ; en partie : la moitié).'),
  yourPick: B('Your answer', 'Votre réponse'),
  noAnswer: B('No answer', 'Sans réponse'),
  rightAnswer: B('Right answer', 'Bonne réponse'),
  draftNote: B('Write your answers on paper, as on exam day, then compare them with the correction.', 'Rédigez vos réponses sur papier, comme le jour de l\'examen, puis comparez-les à la correction.'),
  selfAssess: B('Compare with your answer', 'Comparez avec votre réponse'),
  pastMocks: B('Your mock exams', 'Vos épreuves blanches'),
  again: B('Take another mock exam', 'Passer une autre épreuve blanche'),
  examOverview: B('All the exams', 'Tous les examens'),
  noMockOral: B('An oral is prepared aloud: work through the lessons, then present them to someone at home.', 'Un oral se prépare à voix haute : travaillez les leçons, puis présentez-les à quelqu\'un de votre entourage.'),
  mockSaved: B('Score recorded. A parent can validate it in the parents\' space.', 'Note enregistrée. Un parent peut la valider dans l\'Espace parents.'),
}
